server:
  servlet:
    context-path: /common-library

spring:
  application:
    name: common-library
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/SEP490


cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

keycloak:

  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token



  scope: openid