server:
  servlet:
    context-path: /common-library

spring:
  application:
    name: common-library
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/SEP490
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9094

cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

keycloak:
  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token
  scope: openid

aes:
  secret:
    key: 72Gs15WEFAEQqF2web3cTmhBiZVlri9JqQStJhRsPYYXsmYAakrDEsFw9MU31CUr
  algorithm: AES
  cipher: AES/CBC/PKCS5Padding
  iv-length: 16
